apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    app: server
spec:
  containers:
  - name: server
    image: "alladio/hello-go2"
  #   resources:
  #     limits:
  #       memory: "128Mi"
  #       cpu: "500m"
  #   ports:
  #     - containerPort: <Port>
