apiVersion: v1
kind: Service
metadata:
  name: server-service2
spec:
  selector:
    app: goserver
  type: ClusterIP
  ports:
  - name: server-service
    port: 80
    targetPort: 8000
    protocol: TCP

